# Use postgres/example user/password credentials
version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_PASSWORD: my_password
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username=postgres",
          "--host=127.0.0.1",
          "--port=5433",
        ]
      interval: 30s
      timeout: 1m
      retries: 5
      start_period: 30s

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8050:8080
