module.exports = {
  FEATURE_FLAG_DB: [
    {
      name: "new-feature",
      enabled: true,
      project: "api",
      environment: "local",
      description: "new api",
      lastToogle: "2023-05-28T06:44:06.829Z",
    },
    {
      name: "show-feature",
      enabled: false,
      project: "demo",
      environment: "local",
      description: "demo project",
      lastToogle: "2023-05-28T06:44:06.829Z",
    },
    {
      name: "hide-feature",
      enabled: false,
      project: "dark",
      environment: "local",
      description: "dark project",
      lastToogle: "2023-05-28T06:44:06.829Z",
    },
    {
      name: "security-feature",
      enabled: true,
      project: "dark",
      environment: "local",
      description: "dark project",
      lastToogle: "2023-05-28T06:44:06.829Z",
    },
    {
      name: "cicd-feature",
      enabled: true,
      project: "dark",
      environment: "local",
      description: "dark project",
      lastToogle: "2023-05-28T06:44:06.829Z",
    },
    {
      name: "monitoring-feature",
      enabled: true,
      project: "api",
      environment: "local",
      description: "api for auth",
      lastToogle: "2023-05-28T06:44:06.829Z",
    },
    {
      name: "monitoring-feature",
      enabled: true,
      project: "server",
      environment: "local",
      description: "node server",
      lastToogle: "2023-05-28T06:44:06.829Z",
    },
  ],
};
