### health check
GET http://localhost:3009/health HTTP/1.1
### 
GET http://localhost:3009
###
POST http://localhost:3009/feature-api
###
POST http://localhost:3009/feature-flags HTTP/1.1
content-type: application/json

{"featureEnable": true}
###
POST http://localhost:3009/feature-flags HTTP/1.1
content-type: application/json

{"featureEnable": false}
### feature-flags
POST http://localhost:3009/feature-flags HTTP/1.1
content-type: application/json

{
    "featureEnable": true,
    "featureByProject": "dark"
}
### create-feature-flag
POST http://localhost:3009/app/v1/create-feature-flag HTTP/1.1
content-type: application/json

{
    "name": "grafana_monitoring",
    "enabled": true,
    "project": "observability",
    "environment": "plab",
    "description": "This is a observability feature"
}
### read-feature-flag
POST http://localhost:3009/app/v1/read-feature-flag HTTP/1.1
content-type: application/json

{
    "name": "secure_auth",
    "enabled": true,
    "project": "dark",
    "environment": "local"
}
###
POST http://localhost:3009/app/v1/feature-flags HTTP/1.1
content-type: application/json

{
    "featureEnable": true,
    "featureByProject": "dark"
}
### read-feature-flag?
GET http://localhost:3009/app/v1/read-feature-flag?name=api_monitoring
### read-feature-flag?
GET http://localhost:3009/app/v1/read-feature-flag?name=api_monitoring&enabled=true
### read-feature-flag?
GET http://localhost:3009/app/v1/read-feature-flag?name=graceful_shutdown&enabled=false
### toggle-feature-flag
POST http://localhost:3009/app/v1/toggle-feature-flag HTTP/1.1
content-type: application/json

{
    "name": "api_monitoring3",
    "enabled": true,
    "project": "apm",
    "environment": "prod",
    "description": "new apm project",
    "user_name": "admin"
}
###
GET http://localhost:3009/app/v1/read-feature-flag?name=secure_auth

###
GET http://localhost:3009/app/v1/toggle-audit
### Delete
DELETE http://localhost:3009/app/v1/delete-feature-flag HTTP/1.1
content-type: application/json

{
    "featureName": "api_monitoring2",
    "environment": "prod"
}